name: Android APK Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Check Files in Repository
        run: ls -la && ls -la android/

      - name: Ensure Gradle Wrapper Exists
        run: |
          if [ ! -f "./gradlew" ] && [ ! -f "./android/gradlew" ]; then
            echo "❌ ERROR: gradlew not found! Make sure it exists in the repo."
            exit 1
          fi

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew || chmod +x ./android/gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug || ./android/gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          
